version: '3'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - ./data:/var/lib/registry

  nginx:
    image: nginx:alpine
    container_name: registry-nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
      - ./auth:/etc/nginx/auth
    depends_on:
      - registry

  ui:
    image: joxit/docker-registry-ui:2.5.7
    container_name: registry-ui
    restart: always
    ports:
      - "8080:80"
    environment:
      - REGISTRY_TITLE=My Docker Registry
      - DELETE_IMAGES=true
      - SINGLE_REGISTRY=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
